// Evaluate complete chronological subsets; no graph approximation of changeovers.
export const LIMITS=Object.freeze({roles:16,appearances:128,seconds:86400,inputBytes:1048576,maxMs:8000,maxChecks:30000000});
const cmp=(a,b)=>a<b?-1:a>b?1:0;
export class InputError extends Error{constructor(message){super(message);this.name='InputError';}}
function assert(ok,message){if(!ok)throw new InputError(message);}
function integer(v,min,max,label){assert(Number.isInteger(v)&&v>=min&&v<=max,`${label}: integer ${min}–${max} required`);return v;}
function wellFormed(v){for(let i=0;i<v.length;i++){const c=v.charCodeAt(i);if(c>=0xd800&&c<=0xdbff){const next=v.charCodeAt(++i);if(!(next>=0xdc00&&next<=0xdfff))return false;}else if(c>=0xdc00&&c<=0xdfff)return false;}return true;}
function text(v,max,label){assert(typeof v==='string'&&wellFormed(v)&&v.length<=max&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(v),`${label}: invalid text (max ${max})`);return v.replace(/\r\n?/g,'\n');}
export function normalize(input){
 assert(input&&typeof input==='object'&&!Array.isArray(input),'A recipe object is required');assert(input.modelVersion===undefined||input.modelVersion===1,'Unsupported model version');
 assert(Array.isArray(input.roles)&&input.roles.length>=1&&input.roles.length<=16,'1–16 roles required');const ids=new Set();
 const roles=input.roles.map(r=>{assert(r&&typeof r==='object','Invalid role');const id=text(r.id,32,'Role ID');assert(/^[A-Za-z0-9][A-Za-z0-9_-]*$/.test(id),'Role IDs: ASCII letters, digits, _ or -');assert(!ids.has(id),`Duplicate role ID: ${id}`);ids.add(id);return {id,name:text(r.name??id,80,'Role name')};}).sort((a,b)=>cmp(a.id,b.id));
 assert(Array.isArray(input.appearances)&&input.appearances.length>=1&&input.appearances.length<=128,'1–128 appearances required');const aids=new Set(),seen=new Set();
 const appearances=input.appearances.map(a=>{assert(a&&typeof a==='object','Invalid appearance');const id=text(a.id,32,'Appearance ID');assert(/^[A-Za-z0-9][A-Za-z0-9_-]*$/.test(id),'Appearance IDs: ASCII letters, digits, _ or -');assert(!aids.has(id),`Duplicate appearance ID: ${id}`);aids.add(id);assert(ids.has(a.roleId),`Unknown appearance role: ${a.roleId}`);seen.add(a.roleId);const start=integer(a.start,0,86400,'Entrance'),end=integer(a.end,0,86400,'Exit');assert(start<end,`Appearance ${id}: entrance must precede exit`);return {id,roleId:a.roleId,start,end,cue:text(a.cue??'',500,'Cue')};}).sort((a,b)=>a.start-b.start||a.end-b.end||cmp(a.id,b.id));
 assert(roles.every(r=>seen.has(r.id)),'Every role needs at least one appearance');const defaultChangeover=integer(input.defaultChangeover,0,86400,'Default changeover'),targetTracks=integer(input.targetTracks,1,16,'Target tracks');const overrides=input.overrides??[];assert(Array.isArray(overrides)&&overrides.length<=256,'At most 256 directed overrides');const keys=new Set();
 const normalizedOverrides=overrides.map(o=>{assert(o&&ids.has(o.from)&&ids.has(o.to),'Override references unknown role');assert(o.from!==o.to,'Same-role changeover is fixed at zero');const key=o.from+'>'+o.to;assert(!keys.has(key),`Duplicate override ${key}`);keys.add(key);return {from:o.from,to:o.to,seconds:integer(o.seconds,0,86400,'Override')};}).sort((a,b)=>cmp(a.from,b.from)||cmp(a.to,b.to));
 function pairs(value,kind,max){const arr=value??[];assert(Array.isArray(arr)&&arr.length<=max,`Too many ${kind} constraints`);return arr.map(g=>{assert(Array.isArray(g)&&g.length>=2&&g.length<=(kind==='never-share'?2:16),`Invalid ${kind} group`);assert(g.every(id=>ids.has(id)),`Unknown role in ${kind}`);assert(new Set(g).size===g.length,`Repeated role in ${kind}`);return [...g].sort(cmp);}).sort((a,b)=>cmp(a.join(','),b.join(',')));}
 return {modelVersion:1,roles,appearances,defaultChangeover,overrides:normalizedOverrides,mustShare:pairs(input.mustShare,'must-share',32),neverShare:pairs(input.neverShare,'never-share',120),targetTracks};
}
export function requiredSeconds(model,from,to){if(from===to)return 0;return model.overrides.find(o=>o.from===from&&o.to===to)?.seconds??model.defaultChangeover;}
export function trackDetails(model,roleIds,id='T1'){const set=new Set(roleIds),appearances=model.appearances.filter(a=>set.has(a.roleId));const transitions=appearances.slice(1).map((b,i)=>{const a=appearances[i],gap=b.start-a.end,required=requiredSeconds(model,a.roleId,b.roleId);return {fromId:a.id,toId:b.id,fromRole:a.roleId,toRole:b.roleId,exit:a.end,entrance:b.start,gap,required,slack:gap-required};});return {id,roleIds:[...roleIds],appearances,transitions};}
export function solve(input,options={}){
 const model=normalize(input),started=performance.now();let checks=0;const maxMs=options.maxMs??LIMITS.maxMs,maxChecks=options.maxChecks??LIMITS.maxChecks,n=model.roles.length,total=1<<n,full=total-1,idx=new Map(model.roles.map((r,i)=>[r.id,i])),roleBits=new Map(model.roles.map((r,i)=>[r.id,1<<i]));
 const parent=Array.from({length:n},(_,i)=>i);function root(i){while(parent[i]!==i)i=parent[i];return i;}for(const g of model.mustShare){const a=root(idx.get(g[0]));for(const id of g.slice(1))parent[root(idx.get(id))]=a;}const groups=new Map();for(let i=0;i<n;i++){const r=root(i);groups.set(r,(groups.get(r)??0)|(1<<i));}const groupMasks=[...groups.values()],never=model.neverShare.map(([a,b])=>roleBits.get(a)|roleBits.get(b)),app=model.appearances.map(a=>({...a,bit:roleBits.get(a.roleId)})),requirements=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>requiredSeconds(model,model.roles[i].id,model.roles[j].id)));
 let phase='subsets';const stop={};function tick(force=false){checks++;if(force||(checks&4095)===0){if(checks>maxChecks||performance.now()-started>maxMs)throw stop;options.onProgress?.({phase,checks,elapsedMs:Math.round(performance.now()-started)});}}
 const feasible=new Uint8Array(total);let feasibleCount=0;const memo=new Int8Array(total).fill(-1),choice=new Uint32Array(total);memo[0]=0;
 try{tick(true);for(let mask=1;mask<total;mask++){tick();if(groupMasks.some(g=>(mask&g)!==0&&(mask&g)!==g)||never.some(p=>(mask&p)===p))continue;let previous=null,valid=true;for(const a of app){tick();if(!(mask&a.bit))continue;if(previous){const gap=a.start-previous.end,req=requirements[idx.get(previous.roleId)][idx.get(a.roleId)];if(gap<0||gap<req){valid=false;break;}}previous=a;}if(valid){feasible[mask]=1;feasibleCount++;}}
 phase='partition';tick(true);function dp(mask){tick();if(memo[mask]>=0)return memo[mask];if(feasible[mask]){choice[mask]=mask;return memo[mask]=1;}const anchor=mask&-mask;let best=127,selected=0;for(let sub=mask;sub;sub=(sub-1)&mask){tick();if(!(sub&anchor)||!feasible[sub])continue;const rest=dp(mask^sub);if(rest===127)continue;const score=rest+1;if(score<best||(score===best&&sub<selected)){best=score;selected=sub;}}choice[mask]=selected;return memo[mask]=best;}
 const minimum=dp(full);tick(true);const stats={checks,feasibleSubsets:feasibleCount,elapsedMs:Math.round(performance.now()-started)};if(minimum===127)return {status:'infeasible',minimumTracks:null,targetSufficient:false,tracks:[],stats,model};const tracks=[];let mask=full;while(mask){const sub=choice[mask];if(!sub)throw Error('Partition witness invariant failed');tracks.push(trackDetails(model,model.roles.filter((r,i)=>sub&(1<<i)).map(r=>r.id),`T${tracks.length+1}`));mask^=sub;}return {status:'optimal',minimumTracks:minimum,targetSufficient:minimum<=model.targetTracks,tracks,stats,model};
 }catch(e){if(e!==stop)throw e;return {status:'incomplete',minimumTracks:null,targetSufficient:null,tracks:[],reason:'resource-limit',stats:{checks,feasibleSubsets:feasibleCount,elapsedMs:Math.round(performance.now()-started)},model};}
}
